# Generated by Django 5.2.7 on 2025-10-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_name", models.CharField(max_length=100)),
                ("appointment_time", models.DateTimeField()),
                ("client_email", models.EmailField(max_length=254)),
            ],
        ),
    ]
